# Generated by Django 5.2.17 on 2026-08-19 10:26

import re
from django.db import migrations


def update_notifications(apps, schema_editor):
    Notification = apps.get_model('core', 'Notification')
    for n in Notification.objects.all():
        new_title = re.sub(r'#(\d+)', r'#GB\1', n.title)
        new_body = re.sub(r'#(\d+)', r'#GB\1', n.body)
        if new_title != n.title or new_body != n.body:
            n.title = new_title
            n.body = new_body
            n.save(update_fields=['title', 'body', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffprofile_image'),
    ]

    operations = [
        migrations.RunPython(update_notifications, reverse_code=migrations.RunPython.noop),
    ]
