# Generated by Django 5.2.17 on 2026-08-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_rejected_at_booking_rejected_by_and_more'),
        ('core', '0007_customercylinderdiscount'),
    ]

    operations = [
    ]
