# Generated by Django 5.2.17 on 2026-10-07 20:21
"""Deletion policy (finalSpec §6/§9).

State-only on_delete changes (Django enforces on_delete in Python, no SQL is emitted):
CASCADE -> PROTECT for Booking.customer, Sale.customer, Sale.sold_by, Payment.customer,
Payment.received_by, Delivery.staff, Expense.spent_by; CASCADE -> SET_NULL for
ActivityLog.user. Plus a data fix clearing stale ``rejected_*`` values left on bookings
that are no longer in ``rejected`` status (the old staff-decline path wrote them).
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_stale_rejection_fields(apps, schema_editor):
    Booking = apps.get_model("core", "Booking")
    Booking.objects.exclude(status="rejected").update(
        rejection_reason=None,
        rejected_by=None,
        rejected_by_role=None,
        rejected_at=None,
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20260821_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.customerprofile'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='spent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.customerprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customerprofile'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(clear_stale_rejection_fields, noop),
    ]
